version: "3.3"

services:
  backend-service:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    networks:
      - manager-portal_my-network
    ports:
      - "8000:8000"
networks:
  manager-portal_my-network:
    external: true
